### ISSUE TITLE
Terminal border visibility

### ISSUE THREAD

**Issue by ghost** [a5hk/ice#1]
Hi, I am a big fan of your theme colors, but there is no visible border between the editor and the terminal panel, or between split terminals. This makes it really difficult to adjust panel sizes. Would you consider setting a border color here?

**Comment by a5hk** [comment]
I have added a more contrasted variant of theme. To use it, after updating to the latest version of Ice theme, set your color theme to "Ice Contrast".

![ice-contrast](https://user-images.githubusercontent.com/5412540/84871899-5e2fdf00-b096-11ea-887e-e858bd65794b.PNG)

**Comment by ghost** [comment]
Thank you, that looks great!
